default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: gulshan
  host: localhost
  port: 5432

development:
  <<: *default
  database: spree_dev

test:
  <<: *default
  database: spree_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  url: postgres://medyybcxbowscf:63f56d5c97ad1fd609689ed69ea8b18087e10fd1e9f6d417dcb327816fe8b811@ec2-184-72-248-8.compute-1.amazonaws.com:5432/d28fk371d5vu8f
  database: d28fk371d5vu8f
  username: medyybcxbowscf
  password: 63f56d5c97ad1fd609689ed69ea8b18087e10fd1e9f6d417dcb327816fe8b811